name: Terraform checks and deployment

on:
    pull_request:
      branches:
        - master
    push:
      branches:
        - master

permissions:
  id-token: write
  contents: read

env:
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
    terraform-check:
        name: Terraform format check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.9.6

            - name: Terraform format check
              run: terraform fmt -check -list=false
    
    terraform-plan:
        name: Terraform plan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.9.6

            - name: Configure AWS access
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  audience: sts.amazonaws.com
                  aws-region: us-east-1
                  role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
            - name: Terraform init
              run: terraform init
            
            - name: Terraform plan
              run: terraform plan
    
    terraform-apply:
        name: Terraform apply
        runs-on: ubuntu-latest
        needs: terraform-plan
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.9.6
            - name: Configure AWS access
            uses: aws-actions/configure-aws-credentials@v4
            with:
                audience: sts.amazonaws.com
                aws-region: us-east-1
                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
                    
            - name: Terraform init
              run: terraform init
            
            - name: Terraform apply
              run: terraform apply -auto-approve